-- CRM operacional v1 — evolução aditiva da tabela de oportunidades.
-- Mantém isolamento por conta e não ativa o módulo em nenhuma conta.

alter table public.oportunidades
  add column if not exists campanha_id bigint references public.prospecta_campanhas(id) on delete set null,
  add column if not exists probabilidade integer not null default 5,
  add column if not exists tags text[] not null default '{}'::text[],
  add column if not exists motivo_perda text;

alter table public.oportunidades
  drop constraint if exists oportunidades_probabilidade_check;
alter table public.oportunidades
  add constraint oportunidades_probabilidade_check
  check (probabilidade between 0 and 100);

create index if not exists oportunidades_campanha_idx
  on public.oportunidades (conta_id, campanha_id);

-- Compatibilidade com os dois nomes usados pelo protótipo anterior.
update public.oportunidades set estagio = 'contatado' where estagio = 'contato';
update public.oportunidades set estagio = 'qualificando' where estagio = 'negociacao';

create table if not exists public.crm_atividades (
  id bigint generated by default as identity primary key,
  conta_id uuid not null references public.contas(id) on delete cascade,
  oportunidade_id bigint not null references public.oportunidades(id) on delete cascade,
  autor_id uuid references public.perfis(id) on delete set null,
  tipo text not null default 'nota',
  titulo text not null,
  descricao text,
  concluida boolean not null default false,
  vence_em timestamptz,
  criado_em timestamptz not null default now(),
  constraint crm_atividades_tipo_check
    check (tipo in ('nota', 'tarefa', 'ligacao', 'reuniao', 'email', 'whatsapp'))
);

create index if not exists crm_atividades_oportunidade_idx
  on public.crm_atividades (conta_id, oportunidade_id, criado_em desc);

alter table public.crm_atividades enable row level security;

drop policy if exists crm_atividades_por_conta on public.crm_atividades;
create policy crm_atividades_por_conta on public.crm_atividades for all to authenticated
  using (conta_id = public.minha_conta() or public.sou_super_admin())
  with check (conta_id = public.minha_conta() or public.sou_super_admin());

grant select, insert, update, delete on public.crm_atividades to authenticated;
grant all privileges on public.crm_atividades to service_role;
grant usage, select on sequence public.crm_atividades_id_seq to authenticated;
grant usage, select on sequence public.crm_atividades_id_seq to service_role;

notify pgrst, 'reload schema';
